{
  "jobs": {
    "v02_1-slink": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "run": "docker pull debian/eol:slink\ndocker run --privileged --workdir /github/workspace --rm -e HOME -v /home/runner/work/_temp/_github_home:/github/home -v /home/runner/work/_temp/_github_workflow:/github/workflow -v \"$PWD\":/github/workspace debian/eol:slink sh .extra/debeol.sh slink 2.1"
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v02_2-potato": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:potato",
          "with": {
            "args": "sh .extra/debeol.sh potato 2.2"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v03_0-woody": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:woody",
          "with": {
            "args": "sh .extra/debeol.sh woody 3.0"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v03_1-sarge": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:sarge",
          "with": {
            "args": "sh .extra/debeol.sh sarge 3.1"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v04-etch": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:etch",
          "with": {
            "args": "sh .extra/debeol.sh etch 4"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v05-lenny": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:lenny",
          "with": {
            "args": "sh .extra/debeol.sh lenny 5"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v06-squeeze": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:squeeze",
          "with": {
            "args": "sh .extra/debeol.sh squeeze 6"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v07-wheezy": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:wheezy",
          "with": {
            "args": "sh .extra/debeol.sh wheezy 7"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v08-jessie": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:jessie",
          "with": {
            "args": "sh .extra/debeol.sh jessie 8"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v09-stretch": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian/eol:stretch",
          "with": {
            "args": "sh .extra/debeol.sh stretch 9"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v10-buster": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian:buster",
          "with": {
            "args": "sh .extra/debeol.sh buster 10"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v11-bullseye": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian:bullseye",
          "with": {
            "args": "sh .extra/debeol.sh bullseye 11"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "v12-bookworm": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "uses": "docker://debian:bookworm",
          "with": {
            "args": "sh .extra/debeol.sh bookworm 12"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    }
  },
  "name": "deb-eol",
  "on": {
    "push": {
      "branches": [
        "GHA"
      ]
    },
    "workflow_dispatch": null
  }
}
