{
  "jobs": {
    "g++03": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++03"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "g++11": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++11"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "g++14": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++14"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "g++17": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++17"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "g++20": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++20"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "g++23": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++2b"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "g++98": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c++98"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "gcc11": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c11"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "gcc17": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c17"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "gcc23": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c2x"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "gcc89": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c89"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "gcc99": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh -std=c99"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    }
  },
  "name": "gcc-deb-i386",
  "on": {
    "push": {
      "branches": [
        "GHA"
      ]
    },
    "workflow_dispatch": null
  }
}
