{
  "jobs": {
    "i386-default": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .github/i386.sh"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "i386-default-asan": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .github/i386.sh asan"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "i386-lfs": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .github/i386.sh lfs"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "i386-lfs-asan": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .github/i386.sh lfs asan"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    }
  },
  "name": "deb-i386",
  "on": {
    "workflow_dispatch": null
  }
}
