{
  "jobs": {
    "clang-cxx03": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++03"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang-cxx11": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++11"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang-cxx14": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++14"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang-cxx17": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++17"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang-cxx20": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++20"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang-cxx2b": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++2b"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang-cxx98": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c++98"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang11": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c11"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang17": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c17"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang89": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c89"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    },
    "clang99": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3"
        },
        {
          "uses": "docker://i386/debian:sid-slim",
          "with": {
            "args": "sh .extra/i386.sh clang -std=c99"
          }
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    }
  },
  "name": "clang-deb-i386",
  "on": {
    "workflow_dispatch": null
  }
}
