{
  "jobs": {
    "build": {
      "runs-on": "windows-11-arm",
      "steps": [
        {
          "name": "unfuck line endings (GitHub by default converts them on checkout)",
          "run": "git config --global core.autocrlf false\ngit config --global core.eol lf"
        },
        {
          "uses": "actions/checkout@v4.2.2"
        },
        {
          "id": "setup-msys2",
          "uses": "msys2/setup-msys2@v2",
          "with": {
            "install": "bc ed"
          }
        },
        {
          "name": "prepare arm64 C",
          "run": "find-cl.bat arm64",
          "shell": "cmd"
        },
        {
          "name": "build arm64 C",
          "run": "mkt-int.bat -msys",
          "shell": "cmd"
        },
        {
          "name": "prepare arm64 C++",
          "run": "find-cl.bat arm64",
          "shell": "cmd"
        },
        {
          "name": "build arm64 C++",
          "run": "mkt-int.bat -cxx -msys",
          "shell": "cmd"
        }
      ],
      "strategy": {
        "fail-fast": true
      }
    }
  },
  "name": "Windows/ARM",
  "on": {
    "workflow_dispatch": null
  }
}
